name: Release on Tag (vMajor.Minor.Patch)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Verificar se o commit está na branch main
        id: check_main
        run: |
            echo "GITHUB_REF: $GITHUB_REF"
            echo "GITHUB_SHA: $GITHUB_SHA"
            git show-ref | grep "$(echo $GITHUB_SHA | cut -c1-7)"
            git log --oneline -5

            git fetch origin main

            git checkout -b main origin/main

            cat << 'EOF' > check_commit_in_main.sh
            #!/usr/bin/env bash
            if git rev-list main | grep "$GITHUB_SHA"; then
              echo "Commit está em main!"
            else
              echo "A tag não aponta para um commit em main."
              exit 1
            fi
            EOF

            chmod +x check_commit_in_main.sh
            ./check_commit_in_main.sh
            rm ./check_commit_in_main.sh

      - name: Criar Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}       # O nome da tag do push, ex: "v1.2.3"
          release_name: "Release ${{ github.ref_name }}"
          body: "Release gerada a partir do push de tag na branch main."
          draft: false
          prerelease: false